/*
    vistas generadas para cada ciudad
*/

/* SCRIPT DE VISTAS GLOBALES
   Une los fragmentos de perro1, perro2, perro3 y perro4.
*/

-- 1. VISTA GLOBAL DE CLIENTES
CREATE OR REPLACE VIEW V_CLIENTES AS
SELECT * FROM perro1.CLIENTES
UNION ALL
SELECT * FROM perro2.CLIENTES
UNION ALL
SELECT * FROM perro3.CLIENTES
UNION ALL
SELECT * FROM perro4.CLIENTES;

-- 2. VISTA GLOBAL DE SUCURSALES
CREATE OR REPLACE VIEW V_SUCURSALES AS
SELECT * FROM perro1.SUCURSALES
UNION ALL
SELECT * FROM perro2.SUCURSALES
UNION ALL
SELECT * FROM perro3.SUCURSALES
UNION ALL
SELECT * FROM perro4.SUCURSALES;

-- 3. VISTA GLOBAL DE EMPLEADOS
CREATE OR REPLACE VIEW V_EMPLEADOS AS
SELECT * FROM perro1.EMPLEADOS
UNION ALL
SELECT * FROM perro2.EMPLEADOS
UNION ALL
SELECT * FROM perro3.EMPLEADOS
UNION ALL
SELECT * FROM perro4.EMPLEADOS;

-- 4. VISTA GLOBAL DE VINOS
CREATE OR REPLACE VIEW V_VINOS AS
SELECT * FROM perro1.VINOS
UNION ALL
SELECT * FROM perro2.VINOS
UNION ALL
SELECT * FROM perro3.VINOS
UNION ALL
SELECT * FROM perro4.VINOS;

-- 5. VISTA GLOBAL DE SOLICITUD
CREATE OR REPLACE VIEW V_SOLICITUD AS
SELECT * FROM perro1.SOLICITUD
UNION ALL
SELECT * FROM perro2.SOLICITUD
UNION ALL
SELECT * FROM perro3.SOLICITUD
UNION ALL
SELECT * FROM perro4.SOLICITUD;

-- 6. VISTA GLOBAL DE SUMINISTRO
CREATE OR REPLACE VIEW V_SUMINISTRO AS
SELECT * FROM perro1.SUMINISTRO
UNION ALL
SELECT * FROM perro2.SUMINISTRO
UNION ALL
SELECT * FROM perro3.SUMINISTRO
UNION ALL
SELECT * FROM perro4.SUMINISTRO;

-- 7. VISTA GLOBAL DE PEDIDO
CREATE OR REPLACE VIEW V_PEDIDO AS
SELECT * FROM perro1.PEDIDO
UNION ALL
SELECT * FROM perro2.PEDIDO
UNION ALL
SELECT * FROM perro3.PEDIDO
UNION ALL
SELECT * FROM perro4.PEDIDO;

-- 8. PRODUCTORES (Caso Especial: Replicada)
-- Como la tabla es idéntica en todos sitios, la vista global 
-- simplemente apunta a TU propia tabla local para ser más eficiente.
CREATE OR REPLACE VIEW V_PRODUCTORES AS
SELECT * FROM PRODUCTORES;